package io.harness.rest.helper.rbac;

public enum AccountPermissions {
  CREATE_APPLICATION,
  DELETE_APPLICATION,
  READ_USER_GROUPS,
  MANAGE_USERS_GROUP,
  MANAGE_TAGS,
  MANAGE_TEMPLATE_LIBRARY,
  ADMIN_OTHER_ACCOUNT_FUNCTIONS,
  VIEW_AUDIT_TRIAL,
  MANAGE_CLOUD_PROVIDERS,
  MANAGE_CONNECTORS,
  MANAGE_SECRET_MANAGERS,
  MANAGE_SECRETS,
  CE_ADMIN,
  CE_OWNER

}
